/*
 * KEYPAD.c
 *
 *  Created on: Oct 14, 2022
 *      Author: UWU
 */


#include "KEYPAD.h"


void KEYPAD_INIT()
{
	DIO_SetPinDir(KEYPAD_PORT,DIO_PIN_OUTPUT, KEYPAD_CLO0);
	DIO_SetPinDir(KEYPAD_PORT,DIO_PIN_OUTPUT, KEYPAD_CLO1);
	DIO_SetPinDir(KEYPAD_PORT,DIO_PIN_OUTPUT, KEYPAD_CLO2);
	DIO_SetPinDir(KEYPAD_PORT,DIO_PIN_OUTPUT, KEYPAD_CLO3);

	DIO_SetPinDir(KEYPAD_PORT,DIO_PIN_INPUT, KEYPAD_ROW0);
	DIO_SetPinDir(KEYPAD_PORT,DIO_PIN_INPUT, KEYPAD_ROW1);
	DIO_SetPinDir(KEYPAD_PORT,DIO_PIN_INPUT, KEYPAD_ROW2);
	DIO_SetPinDir(KEYPAD_PORT,DIO_PIN_INPUT, KEYPAD_ROW3);


}
uint8 KEYPAD_GET_VAL()
{

}
